#!/bin/bash

image_folder="/home/maymoona/Pictures/Wallpapers/JPG/"
# set monitor to mirror mode
xrandr --output eDP-1 --auto --output HDMI-1 --auto --same-as eDP-1

# set monitor to extend mode
# xrandr --output eDP-1 --auto --output DP-1 --auto --right-of eDP-1

# select a random image from the folder
random_image=$(find "$image_folder" -type f -name "*.jpg" | shuf -n 1)
echo "selected image: ${random_image}"

wal -n -i "${randome_image}"
nohup ~/.config/i3/polybar/launch.sh &
feh --bg-scale "${randome_image}"
