#!/bin/bash

# Set a random background without setting up the screens
image_folder="/home/maymoona/Pictures/Wallpapers/JPG/"

# Get a random image using shuf
random_image=$(find "$image_folder" -type f -name "*.jpg" | shuf -n 1)
echo "Setting background to $random_image"

# Apply the selected image
wal -n -i "$random_image"
nohup ~/.config/i3/polybar/launch.sh &
feh --bg-scale "$random_image"
