#!/bin/bash

# just sets a random bg without setting up the screens
image_folder="/home/maymoona/Pictures/Wallpapers/JPG/"

images=(${image_folder}*.jpg)
random_num=$((RANDOM % ${#images[@]}))

randome_image=${images[$random_num]}

wal -n -i "${randome_image}"
nohup ~/.config/i3/polybar/launch.sh &
feh --bg-scale "${randome_image}"
